// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Receptserver.Data;

#nullable disable

namespace Receptserver.Data.Migrations
{
    [DbContext(typeof(ReceptDbContext))]
    partial class ReceptDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Receptserver.Core.Entities.Apotek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Apoteker");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresse = "Store Torv 3, 8000 Aarhus",
                            Navn = "Aarhus Apotek"
                        },
                        new
                        {
                            Id = 2,
                            Adresse = "Stadionalle 1, 8240 Risskov",
                            Navn = "Risskov Apotek"
                        },
                        new
                        {
                            Id = 3,
                            Adresse = "Skanderborgvej 220, 8260 Viby",
                            Navn = "Viby Apotek"
                        });
                });

            modelBuilder.Entity("Receptserver.Core.Entities.Laegehus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ydernummer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ydernummer")
                        .IsUnique();

                    b.ToTable("Laegehuse");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresse = "Banegårdsgade 1, 8000 Aarhus",
                            Navn = "Lægerne i Aarhus C",
                            Ydernummer = "012345"
                        },
                        new
                        {
                            Id = 2,
                            Adresse = "Skovvejen 12, 8240 Risskov",
                            Navn = "Risskov Lægehus",
                            Ydernummer = "054321"
                        },
                        new
                        {
                            Id = 3,
                            Adresse = "Skanderborgvej 200, 8260 Viby",
                            Navn = "Viby Lægehus",
                            Ydernummer = "067890"
                        });
                });

            modelBuilder.Entity("Receptserver.Core.Entities.Ordination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AntalForetagneUdleveringer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AntalUdleveringer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dosis")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Laegemiddel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReceptId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReceptId");

                    b.ToTable("Ordinationer");
                });

            modelBuilder.Entity("Receptserver.Core.Entities.Recept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CprNummer")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Lukket")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Oprettelsesdato")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TilknyttetApotekId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ydernummer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CprNummer");

                    b.HasIndex("TilknyttetApotekId");

                    b.ToTable("Recepter");
                });

            modelBuilder.Entity("Receptserver.Core.Entities.Ordination", b =>
                {
                    b.HasOne("Receptserver.Core.Entities.Recept", "Recept")
                        .WithMany("Ordinationer")
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recept");
                });

            modelBuilder.Entity("Receptserver.Core.Entities.Recept", b =>
                {
                    b.HasOne("Receptserver.Core.Entities.Apotek", "TilknyttetApotek")
                        .WithMany()
                        .HasForeignKey("TilknyttetApotekId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TilknyttetApotek");
                });

            modelBuilder.Entity("Receptserver.Core.Entities.Recept", b =>
                {
                    b.Navigation("Ordinationer");
                });
#pragma warning restore 612, 618
        }
    }
}
